import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/my-theme.toml"
]

# "window.dynamic_title" = true

[shell]
# program = "/usr/bin/zsh"
program = "/usr/bin/fish"
# program = "/usr/bin/bash"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 10.5

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 3

[font.bold]
style = "bold"
# family = "JetBrainsMono Nerd Font"
# family = "MesloLGSDZ Nerd Font"
family = "SFMono Nerd Font"

[font.italic]
# family = "JetBrainsMono Nerd Font"
# family = "MesloLGSDZ Nerd Font"
family = "SFMono Nerd Font"
style = "italic"

[font.normal]
# family = "JetBrainsMono Nerd Font"
# family = "MesloLGSDZ Nerd Font"
family = "SFMono Nerd Font"
style = "normal"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity =  0.80
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 5

[env]
term = "alacritty"


